name: yhy_coloring_book_flutter
description: "Coloring book image transformation Flutter App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.0-200.1.beta


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # REQUIRED for localization
    sdk: flutter


  google_sign_in: ^7.2.0
  flutter_facebook_auth: ^7.1.5


  google_fonts: ^6.1.0
  # State Management
  flutter_riverpod: ^2.4.9
  #access gallery and camera
  image_picker: ^1.0.7

  # Data & Device
  http: ^1.2.0
  shared_preferences: ^2.2.2
  device_info_plus: ^10.1.0
  uuid: ^4.3.3
  font_awesome_flutter: ^10.6.0
  cached_network_image: ^3.4.1
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

